### ISSUE TITLE
Context PopupMenu freezes open when first clicked.

### ISSUE THREAD

**Issue by jfaron** [Esri/calcite-maps#158] opened 2017-04-07 01:22 UTC
I originally opened an issue in the cmv-calcite repo regarding the popup menu in their layer control widget [https://github.com/cmv/cmv-calcite-maps/issues/5](url) but have discovered that it is an issue with Calcite even on the Esri sample page.
To see, go to Esri sample [https://developers.arcgis.com/javascript/3/sandbox/sandbox.html?sample=graphics_contextmenu](url) , change the two stylesheet links:
`<link rel="stylesheet" href= "https://js.arcgis.com/3.20/esri/themes/calcite/dijit/calcite.css">
    <link rel="stylesheet" href="https://js.arcgis.com/3.20/esri/themes/calcite/esri/esri.css">`

and the body class tag:
`<body class="calcite" style="font-size: 0.75em;">`

What happens is the first context menu that opens is not in focus, and thus clicking outside the popup menu does nothing. If you open a second menu by clicking a different graphic, then it gets focus and works as expected, or if you click in the first popup it will also get focus. In the cmv app, the behavior is similar when clicking on the menu icon in the layer control widget. It is worse in that app, in that the user could get frustrated since the popup menu will stay open until it gets focus, even if the widget is closed. Hopefully this is a relatively easy fix. Debugging it takes me into esri's menu.js, which is minified.

**Comment by tmcgee** [comment] 2017-04-07 18:02
@jfaron I can duplicate the issue both in CMV+Calcite as well as the Esri demo. The un-minified code for the Menu dijit can be found [here](https://github.com/dojo/dijit) if that helps debug this further.

**Comment by jfaron** [comment] 2017-04-10 00:59
@tmcgee thanks for that. It looks like it may pertain to [this](https://bugs.dojotoolkit.org/ticket/17788) dojo issue. I was planning on doing the dojo build version of CMV sooner or later anyway, so this is a good excuse to do it sooner. It's the only way I can see to try any solutions with menuItem.js, since there is a lot of requiring in the several menu modules that references as relative to the directory. I'll let you know what I find out.

**Comment by alaframboise** [comment] 2017-04-11 21:41
Hey, if you guys can repro this in a JSbin outside of CMV and Calcite Maps let me know.

**Comment by jfaron** [comment] 2017-04-12 00:22
Not sure what you mean by "outside of ... Calcite Maps". It seems the point is that it happens when using Calcite Maps.

**Comment by alaframboise** [comment] 2017-04-12 16:22
@jfaron sorry for the confusion, but this looks like an ArcGIS JS 3.x API "calcite theme" issue as [it can be reproduced](http://jsbin.com/naxisad/edit?html,output) outside of the calcite-maps framework. Therefore, I would recommend submitting this as a core issue to support.

**Comment by jfaron** [comment] 2017-04-13 16:47
Will do, and thanks for the follow up. By the way, I was able to apply the fix suggested [here](https://bugs.dojotoolkit.org/ticket/17788), by using the Bower/dojo build, and indeed the fix suggested by user Inarus does work, and at least up to now does not seem to break anything. @tmcgee, this also fixes the [other issue](https://github.com/cmv/cmv-calcite-maps/issues/2) on cmv-calcite regarding the widgets remaining greyed out after closed. I'll submit all of this to tech support but I'm not optimistic, since this may actually be a Dojo problem, and Dylan did not seem eager to work on it as of 6 months ago. Too bad we didn't have this at the Dev Summit! :).

**Comment by alaframboise** [comment] 2017-04-13 21:03
Thanks for the info. Closing.

**Closed by alaframboise** 2017-04-13 21:03 UTC
